apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: my-app-container
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "256Mi"
            cpu: "1"
        env:
        - name: ENV
          value: prod