apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: my-app
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ= # Base64 encoded "password"
  API_KEY: dG9wLXNlY3JldC1rZXk= # Base64 encoded "top-secret-key"
