name: Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Minikube
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # Step 3: Start Minikube with Docker Driver
      - name: Start Minikube
        run: |
          export MINIKUBE_HOME=${HOME}/.minikube
          export CHANGE_MINIKUBE_NONE_USER=true
          sudo minikube start --driver=docker --wait=apiserver,system_pods,default_sa --force --profile=minikube

      # Step 4: Configure kubectl to Use Minikube
      - name: Set Up kubectl for Minikube
        run: |
          export KUBECONFIG=${HOME}/.kube/config
          mkdir -p ${HOME}/.kube
          sudo minikube --profile=minikube config view --flatten > ${HOME}/.kube/config
          kubectl config use-context minikube
          echo "kubectl is now configured to use Minikube!"

      # Step 5: Apply Kubernetes Manifests
      - name: Deploy Application
        env:
          KUBECONFIG: ${HOME}/.kube/config
        run: |
          kubectl apply -k overlays/dev

      # Step 6: Verify Deployment
      - name: Verify Deployment
        env:
          KUBECONFIG: ${HOME}/.kube/config
        run: |
          kubectl rollout status deployment/my-app
          kubectl get pods
