name: Deploy Application to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        export MINIKUBE_HOME=${HOME}/.minikube
        export CHANGE_MINIKUBE_NONE_USER=true
        minikube start --driver=docker

    - name: Generate Kubeconfig
      run: |
        mkdir -p ${HOME}/.kube
        cat <<EOF > ${HOME}/.kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/runner/.minikube/ca.crt
    server: https://127.0.0.1:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/runner/.minikube/profiles/minikube/client.crt
    client-key: /home/runner/.minikube/profiles/minikube/client.key
EOF
      echo "Kubeconfig generated successfully!"

    - name: Configure kubectl
      run: |
        kubectl config use-context minikube
        echo "kubectl is configured to use Minikube context."

    - name: Deploy Application
      run: |
        kubectl apply -k overlays/dev
