name: Deploy Application to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Generate kubeconfig
      run: |
        mkdir -p ${HOME}/.kube
        mkdir -p ${HOME}/.minikube
        cp -r /root/.kube/* ${HOME}/.kube/
        cp -r /root/.minikube/* ${HOME}/.minikube/
        sed -i "s|/root|${HOME}|g" ${HOME}/.kube/config
        chmod 600 ${HOME}/.kube/config

    - name: Configure kubectl
      run: |
        kubectl config use-context minikube

    - name: Deploy Application
      run: |
        kubectl apply -k overlays/dev
