name: Deploy Application to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube as Non-Root User
      run: |
        export MINIKUBE_HOME=${HOME}
        minikube start --driver=docker

    - name: Generate kubeconfig
      run: |
        export MINIKUBE_HOME=${HOME}
        mkdir -p ${HOME}/.kube
        cp ${HOME}/.minikube/profiles/minikube/config ${HOME}/.kube/config
        chmod 600 ${HOME}/.kube/config

    - name: Configure kubectl
      run: |
        kubectl config use-context minikube

    - name: Deploy Application
      run: |
        kubectl apply -k overlays/dev
