name: Deploy Application to Minikube

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          export MINIKUBE_HOME=${HOME}/.minikube
          export CHANGE_MINIKUBE_NONE_USER=true
          minikube start --driver=docker

      - name: Set Up Kubeconfig for Minikube
        run: |
          mkdir -p ${HOME}/.kube
          minikube kubeconfig > ${HOME}/.kube/config
          echo "Kubeconfig successfully set up for Minikube!"

      - name: Verify Cluster Context
        run: |
          kubectl config get-contexts
          kubectl config use-context minikube
          kubectl cluster-info

      - name: Deploy Application
        run: |
          kubectl apply -k overlays/dev
