name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create kubeconfig
      run: |
        mkdir -p ${HOME}/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ${HOME}/.kube/config
        sed -i 's|C:\\Users\\HP|/home/runner|g' ${HOME}/.kube/config
        sed -i 's|\\\\|/|g' ${HOME}/.kube/config
        cat ${HOME}/.kube/config

    - name: Set kubectl context
      run: |
        kubectl config use-context minikube

    - name: Deploy with Kustomize
      run: |
        kubectl apply -k overlays/dev
